// <auto-generated />
using System;
using HawaqmAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HawaqmAI.Api.Data.Migrations
{
    [DbContext(typeof(ChatHistoryDbContext))]
    partial class ChatHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("feedback_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("MessageId");

                    b.ToTable("chat_feedback", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_feedback_rating", "rating IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChartData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chart_data");

                    b.Property<string>("ChartType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("chart_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("data_source");

                    b.Property<string>("DateRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("date_range");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model_used");

                    b.Property<string>("ResponseType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("response_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<string>("SqlQuery")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sql_query");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int")
                        .HasColumnName("token_count");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("IX_chat_messages_session");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_messages_role", "role IN ('user', 'assistant')");
                        });
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_message_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int")
                        .HasColumnName("message_count");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope");

                    b.Property<string>("SiteName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("site_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("New conversation")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId", "LastMessageAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_chat_sessions_user");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.UserPin", b =>
                {
                    b.Property<Guid>("PinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pin_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("PinId");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_pins_message_user");

                    b.ToTable("user_pins", (string)null);
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatFeedback", b =>
                {
                    b.HasOne("HawaqmAI.Api.Models.ChatMessage", "Message")
                        .WithMany("Feedback")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatMessage", b =>
                {
                    b.HasOne("HawaqmAI.Api.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.UserPin", b =>
                {
                    b.HasOne("HawaqmAI.Api.Models.ChatMessage", "Message")
                        .WithMany("Pins")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatMessage", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Pins");
                });

            modelBuilder.Entity("HawaqmAI.Api.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
